color0 #1e100e
color1 #ffb4ab
color2 #ffb4a9
color3 #ffb4a9
color4 #ffb952
color5 #ffb4a9
color6 #ffb4a9
color7 #f9dcd8
color8 #ab8984
color9 #ffb4ab
color10 #ffb4a9
color11 #ffb4a9
color12 #ffb952
color13 #ffb4a9
color14 #ffb4a9
color15 #f9dcd8

cursor                #f9dcd8
cursor_text_color     #1e100e
background            #1e100e
foreground            #f9dcd8
selection_foreground  #e4beb8
selection_background  #5b403c
active_border_color   #ffb4a9
inactive_border_color #5b403c
url_color             #ffb4a9

active_tab_foreground   #690001
active_tab_background   #ffb4a9
inactive_tab_foreground #e4beb8
inactive_tab_background #5b403c
cursor_trail_color      #e4beb8
