color0 #14121a
color1 #ffb4ab
color2 #c8bfff
color3 #c8c0f6
color4 #ffabee
color5 #c8bfff
color6 #c8c0f6
color7 #e5e1eb
color8 #928f9f
color9 #ffb4ab
color10 #c8bfff
color11 #c8c0f6
color12 #ffabee
color13 #c8bfff
color14 #c8c0f6
color15 #e5e1eb

cursor                #e5e1eb
cursor_text_color     #14121a
background            #14121a
foreground            #e5e1eb
selection_foreground  #c9c4d5
selection_background  #474553
active_border_color   #c8bfff
inactive_border_color #474553
url_color             #c8bfff

active_tab_foreground   #2d0e94
active_tab_background   #c8bfff
inactive_tab_foreground #c9c4d5
inactive_tab_background #474553
cursor_trail_color      #c9c4d5
