color0 #1b1429
color1 #fd4663
color2 #9267e4
color3 #c35cd6
color4 #cc66aa
color5 #b193ec
color6 #dc96e9
color7 #f2f2f3
color8 #676175
color9 #fd4663
color10 #9267e4
color11 #c35cd6
color12 #cc66aa
color13 #b193ec
color14 #dc96e9
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #1b1429
background            #1b1429
foreground            #f2f2f3
selection_foreground  #b1afb6
selection_background  #241b37
active_border_color   #9267e4
inactive_border_color #241b37
url_color             #9267e4

active_tab_foreground   #1d1825
active_tab_background   #9267e4
inactive_tab_foreground #b1afb6
inactive_tab_background #241b37
cursor_trail_color      #b1afb6
