color0 #1a1727
color1 #fd4663
color2 #a38eeb
color3 #ce95e4
color4 #de9bcf
color5 #a793ec
color6 #d296e9
color7 #f2f2f3
color8 #676278
color9 #fd4663
color10 #a38eeb
color11 #ce95e4
color12 #de9bcf
color13 #a793ec
color14 #d296e9
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #1a1727
background            #1a1727
foreground            #f2f2f3
selection_foreground  #b0afb6
selection_background  #231e34
active_border_color   #a38eeb
inactive_border_color #231e34
url_color             #a38eeb

active_tab_foreground   #0f0d15
active_tab_background   #a38eeb
inactive_tab_foreground #b0afb6
inactive_tab_background #231e34
cursor_trail_color      #b0afb6
