color0 #1b1924
color1 #fd4663
color2 #7e67e4
color3 #b15cd6
color4 #cc66b9
color5 #a393ec
color6 #d096e9
color7 #f2f2f3
color8 #676379
color9 #fd4663
color10 #7e67e4
color11 #b15cd6
color12 #cc66b9
color13 #a393ec
color14 #d096e9
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #1b1924
background            #1b1924
foreground            #f2f2f3
selection_foreground  #b0afb6
selection_background  #242131
active_border_color   #7e67e4
inactive_border_color #242131
url_color             #7e67e4

active_tab_foreground   #1b1825
active_tab_background   #7e67e4
inactive_tab_foreground #b0afb6
inactive_tab_background #242131
cursor_trail_color      #b0afb6
