color0 #14140f
color1 #ffb4ab
color2 #caca8b
color3 #cac8aa
color4 #aad0a7
color5 #caca8b
color6 #cac8aa
color7 #e6e2db
color8 #939183
color9 #ffb4ab
color10 #caca8b
color11 #cac8aa
color12 #aad0a7
color13 #caca8b
color14 #cac8aa
color15 #e6e2db

cursor                #e6e2db
cursor_text_color     #14140f
background            #14140f
foreground            #e6e2db
selection_foreground  #c9c7b7
selection_background  #48473b
active_border_color   #caca8b
inactive_border_color #48473b
url_color             #caca8b

active_tab_foreground   #323203
active_tab_background   #caca8b
inactive_tab_foreground #c9c7b7
inactive_tab_background #48473b
cursor_trail_color      #c9c7b7
