[HighQuality]
glsl-shaders-clr
vf=clr
profile=Balanced
scale-antiring=1
dscale-antiring=1
cscale-antiring=1
video-output-levels=full
hdr-peak-percentile=99.95
hdr-contrast-recovery=0.3
hdr-contrast-smoothness=5.0
allow-delayed-peak-detect=yes
vf-clr

[upmix]
af-clr
af=lavfi=[volume=0.4,pan=5.1| FL = FL | FR = FR | FC < 0.5*FL+0.5*FR | LFE < 0.5*FL+0.5*FR | BL=FL | BR=FR]


[Balanced]
glsl-shaders-clr
vf-clr
scale-antiring=0
dscale-antiring=0
cscale-antiring=0
scale=lanczos
cscale=catmull_rom
dscale=catmull_rom
dither-depth=auto
dither=fruit
target-trc=auto
correct-downscaling=yes
linear-downscaling=no
sigmoid-upscaling=yes
hdr-compute-peak=yes
target-colorspace-hint=yes
hdr-peak-percentile=100
hdr-contrast-recovery=0.0
allow-delayed-peak-detect=no

[Fast]
glsl-shaders-clr
vf=clr
profile-cond=height > 1080
profile=fast
scale-antiring=0
dscale-antiring=0
cscale-antiring=0
scale=bilinear
cscale=bilinear
dscale=bilinear
correct-downscaling=no
linear-downscaling=no
sigmoid-upscaling=no
hdr-compute-peak=no
hdr-peak-percentile=100
hdr-contrast-recovery=0.0
allow-delayed-peak-detect=no
dither=no


[interpolation-activate]
profile-cond=get("interpolation")
profile-restore=copy
glsl-shaders=clr
interpolation=yes
video-sync=display-resample


[extension.gif]
save-position-on-quit=no
loop-file=inf
no-cache

[pip]
profile-restore=copy-equal
ontop
on-all-workspaces
no-force-window-position
geometry=100%:100%
autofit=30%x30%
autofit-smaller=
autofit-larger=

#===== Protocol Specific Configuration =====
 
[protocol.http]
profile-restore=copy-equal 
profile-desc=http
hls-bitrate=max
cache=yes
no-cache-pause

[protocol.https]
profile-restore=copy-equal
profile-desc=https
profile=protocol.http

[protocol.ytdl]
profile-restore=copy-equal
profile-desc=ytdl
profile=protocol.http

[Downmix_Audio_5_1]
profile-restore=copy-equal
af=lavfi="lowpass=c=LFE:f=120,volume=1.6,pan=stereo|FL=0.5*FC+0.707*FL+0.707*BL+0.5*LFE|FR=0.5*FC+0.707*FR+0.707*BR+0.5*LFE"

[Downmix_Audio_7_1]
profile-restore=copy-equal
af=lavfi="lowpass=c=LFE:f=120,volume=1.6,pan=stereo|FL=0.5*FC+0.3*FLC+0.3*FL+0.3*BL+0.3*SL+0.5*LFE|FR=0.5*FC+0.3*FRC+0.3*FR+0.3*BR+0.3*SR+0.5*LFE"
